[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sciform"
version = "0.27.3"
authors = [
    {name = "Justin Gerber", email="justin.gerber48@gmail.com"}
]
description = "A package for formatting numbers into scientific formatted strings."
classifiers = [
    "License :: OSI Approved :: MIT License"
]
dynamic = ["readme"]

[project.urls]
homepage = "https://github.com/jagerber48/sciform"
documentation = "https://sciform.readthedocs.io"

[tool.setuptools.dynamic]
readme = {file = "README.rst"}
